In [1]:
import pymysql
from pandas import DataFrame
import pandas as pd 

host   = 'villagebikesdb.c2v2pmaab8cg.us-east-2.rds.amazonaws.com'
port   = 3306
user   = 'ssk'
passwd = 'villagebikes'
db     = 'VillageBikesDB'

cnx    = pymysql.connect(host=host, port=port, user=user, passwd=passwd, db=db)
cur    = cnx.cursor()

query  = """SELECT * FROM weatherData"""
cur.execute(query)

field_names = [i[0] for i in cur.description]
get_data = [xx for xx in cur]

cur.close()
cnx.close()

df1 = DataFrame(get_data)
df1.columns = field_names
print(df1)

       timestamp  weather_id     main                   description  \
0     1550743200         802   Clouds              scattered clouds
1     1550748600         802   Clouds              scattered clouds
2     1550750400         802   Clouds              scattered clouds
3     1550752200         802   Clouds              scattered clouds
4     1550761200         803   Clouds                 broken clouds
5     1550763000         803   Clouds                 broken clouds
6     1550764800         803   Clouds                 broken clouds
7     1550766600         803   Clouds                 broken clouds
8     1550768400         803   Clouds                 broken clouds
9     1550770200         803   Clouds                 broken clouds
10    1550772000         803   Clouds                 broken clouds
11    1550773800         803   Clouds                 broken clouds
12    1550775600         803   Clouds                 broken clouds
13    1550777400         803   Clouds                 broken clouds
14    1550779200         803   Clouds                 broken clouds
15    1550781000         803   Clouds                 broken clouds
16    1550782800         803   Clouds                 broken clouds
17    1550784600         802   Clouds              scattered clouds
18    1550786400         801   Clouds                    few clouds
19    1550788200         801   Clouds                    few clouds
20    1550790000         802   Clouds              scattered clouds
21    1550791800         802   Clouds              scattered clouds
22    1550793600         803   Clouds                 broken clouds
23    1550795400         802   Clouds              scattered clouds
24    1550797200         802   Clouds              scattered clouds
25    1550799000         803   Clouds                 broken clouds
26    1550800800         803   Clouds                 broken clouds
27    1550802600         803   Clouds                 broken clouds
28    1550804400         803   Clouds                 broken clouds
29    1550806200         803   Clouds                 broken clouds
...          ...         ...      ...                           ...
1739  1553148530         803   Clouds                 broken clouds
1740  1553149719         803   Clouds                 broken clouds
1741  1553151215         803   Clouds                 broken clouds
1742  1553152415         803   Clouds                 broken clouds
1743  1553153336         310  Drizzle  light intensity drizzle rain
1744  1553154820         310  Drizzle  light intensity drizzle rain
1745  1553156025         310  Drizzle  light intensity drizzle rain
1746  1553156618         803   Clouds                 broken clouds
1747  1553158434         803   Clouds                 broken clouds
1748  1553159627         803   Clouds                 broken clouds
1749  1553160824         803   Clouds                 broken clouds
1750  1553162028         803   Clouds                 broken clouds
1751  1553163216         500     Rain                    light rain
1752  1553164435         300  Drizzle       light intensity drizzle
1753  1553165621         300  Drizzle       light intensity drizzle
1754  1553166815         803   Clouds                 broken clouds
1755  1553168028         803   Clouds                 broken clouds
1756  1553169213         803   Clouds                 broken clouds
1757  1553170126         803   Clouds                 broken clouds
1758  1553171621         803   Clouds                 broken clouds
1759  1553172825         803   Clouds                 broken clouds
1760  1553173724         803   Clouds                 broken clouds
1761  1553175217         803   Clouds                 broken clouds
1762  1553176421         803   Clouds                 broken clouds
1763  1553177621         803   Clouds                 broken clouds
1764  1553178526         803   Clouds                 broken clouds
1765  1553180028         803   Clouds                 broken clouds
1766  1553180923         803   Clouds                 broken clouds
1767  1553182420         803   Clouds                 broken clouds
1768  1553183631         803   Clouds                 broken clouds

      temperature  humidity  wind_speed
0          285.13      76.0         3.1
1          285.64      71.0         5.1
2          285.64      71.0         6.2
3          285.64      66.0         5.7
4          286.15      62.0         8.2
5          286.15      62.0         8.7
6          286.15      62.0         8.2
7          285.15      66.0         7.7
8          284.15      71.0         6.2
9          284.15      71.0         7.2
10         284.15      71.0         6.7
11         284.15      71.0         4.6
12         283.15      76.0         5.7
13         283.15      76.0         4.1
14         283.66      81.0         6.2
15         284.15      76.0         7.2
16         283.66      81.0         7.2
17         284.15      76.0         6.2
18         283.66      87.0         5.7
19         284.15      76.0         3.1
20         284.66      81.0         3.1
21         284.29      87.0         3.1
22         284.68      81.0         4.1
23         284.42      87.0         4.1
24         284.70      87.0         2.1
25         286.72      58.0         8.2
26         286.66      62.0         9.8
27         285.86      71.0         9.8
28         286.17      66.0         8.7
29         286.29      62.0         9.8
...           ...       ...         ...
1739       283.37      87.0         3.6
1740       283.26      87.0         4.6
1741       283.26      87.0         4.6
1742       283.15      81.0         5.1
1743       283.15      81.0         3.6
1744       283.36      87.0         3.6
1745       283.36      87.0         3.6
1746       283.67      81.0         3.1
1747       284.06      81.0         3.6
1748       284.06      81.0         3.6
1749       284.33      81.0         3.6
1750       284.48      81.0         3.6
1751       284.33      81.0         3.6
1752       284.86      71.0         3.6
1753       285.09      71.0         3.6
1754       285.09      76.0         3.6
1755       285.55      76.0         2.6
1756       285.76      76.0         2.6
1757       285.97      76.0         3.6
1758       286.07      76.0         3.1
1759       286.09      76.0         3.6
1760       285.96      76.0         3.6
1761       286.15      71.0         3.6
1762       286.35      71.0         2.6
1763       286.35      71.0         2.6
1764       286.54      71.0         3.1
1765       286.46      76.0         3.6
1766       286.58      76.0         3.6
1767       286.46      71.0         3.6
1768       286.45      71.0         3.6

[1769 rows x 7 columns]

In [2]:
df1

,timestamp,weather_id,main,description,temperature,humidity,wind_speed
0,1550743200,802,Clouds,scattered clouds,285.13,76.0,3.1
1,1550748600,802,Clouds,scattered clouds,285.64,71.0,5.1
2,1550750400,802,Clouds,scattered clouds,285.64,71.0,6.2
3,1550752200,802,Clouds,scattered clouds,285.64,66.0,5.7
4,1550761200,803,Clouds,broken clouds,286.15,62.0,8.2
5,1550763000,803,Clouds,broken clouds,286.15,62.0,8.7
6,1550764800,803,Clouds,broken clouds,286.15,62.0,8.2
7,1550766600,803,Clouds,broken clouds,285.15,66.0,7.7
8,1550768400,803,Clouds,broken clouds,284.15,71.0,6.2
9,1550770200,803,Clouds,broken clouds,284.15,71.0,7.2
10,1550772000,803,Clouds,broken clouds,284.15,71.0,6.7
11,1550773800,803,Clouds,broken clouds,284.15,71.0,4.6
12,1550775600,803,Clouds,broken clouds,283.15,76.0,5.7
13,1550777400,803,Clouds,broken clouds,283.15,76.0,4.1
14,1550779200,803,Clouds,broken clouds,283.66,81.0,6.2
15,1550781000,803,Clouds,broken clouds,284.15,76.0,7.2
16,1550782800,803,Clouds,broken clouds,283.66,81.0,7.2
17,1550784600,802,Clouds,scattered clouds,284.15,76.0,6.2
18,1550786400,801,Clouds,few clouds,283.66,87.0,5.7
19,1550788200,801,Clouds,few clouds,284.15,76.0,3.1
20,1550790000,802,Clouds,scattered clouds,284.66,81.0,3.1
21,1550791800,802,Clouds,scattered clouds,284.29,87.0,3.1
22,1550793600,803,Clouds,broken clouds,284.68,81.0,4.1
23,1550795400,802,Clouds,scattered clouds,284.42,87.0,4.1
24,1550797200,802,Clouds,scattered clouds,284.70,87.0,2.1
25,1550799000,803,Clouds,broken clouds,286.72,58.0,8.2
26,1550800800,803,Clouds,broken clouds,286.66,62.0,9.8
27,1550802600,803,Clouds,broken clouds,285.86,71.0,9.8
28,1550804400,803,Clouds,broken clouds,286.17,66.0,8.7
29,1550806200,803,Clouds,broken clouds,286.29,62.0,9.8
...,...,...,...,...,...,...,...
1739,1553148530,803,Clouds,broken clouds,283.37,87.0,3.6
1740,1553149719,803,Clouds,broken clouds,283.26,87.0,4.6
1741,1553151215,803,Clouds,broken clouds,283.26,87.0,4.6
1742,1553152415,803,Clouds,broken clouds,283.15,81.0,5.1
1743,1553153336,310,Drizzle,light intensity drizzle rain,283.15,81.0,3.6
1744,1553154820,310,Drizzle,light intensity drizzle rain,283.36,87.0,3.6
1745,1553156025,310,Drizzle,light intensity drizzle rain,283.36,87.0,3.6
1746,1553156618,803,Clouds,broken clouds,283.67,81.0,3.1
1747,1553158434,803,Clouds,broken clouds,284.06,81.0,3.6
1748,1553159627,803,Clouds,broken clouds,284.06,81.0,3.6
1749,1553160824,803,Clouds,broken clouds,284.33,81.0,3.6
1750,1553162028,803,Clouds,broken clouds,284.48,81.0,3.6
1751,1553163216,500,Rain,light rain,284.33,81.0,3.6
1752,1553164435,300,Drizzle,light intensity drizzle,284.86,71.0,3.6
1753,1553165621,300,Drizzle,light intensity drizzle,285.09,71.0,3.6
1754,1553166815,803,Clouds,broken clouds,285.09,76.0,3.6
1755,1553168028,803,Clouds,broken clouds,285.55,76.0,2.6
1756,1553169213,803,Clouds,broken clouds,285.76,76.0,2.6
1757,1553170126,803,Clouds,broken clouds,285.97,76.0,3.6
1758,1553171621,803,Clouds,broken clouds,286.07,76.0,3.1
1759,1553172825,803,Clouds,broken clouds,286.09,76.0,3.6
1760,1553173724,803,Clouds,broken clouds,285.96,76.0,3.6
1761,1553175217,803,Clouds,broken clouds,286.15,71.0,3.6
1762,1553176421,803,Clouds,broken clouds,286.35,71.0,2.6
1763,1553177621,803,Clouds,broken clouds,286.35,71.0,2.6
1764,1553178526,803,Clouds,broken clouds,286.54,71.0,3.1
1765,1553180028,803,Clouds,broken clouds,286.46,76.0,3.6
1766,1553180923,803,Clouds,broken clouds,286.58,76.0,3.6
1767,1553182420,803,Clouds,broken clouds,286.46,71.0,3.6
1768,1553183631,803,Clouds,broken clouds,286.45,71.0,3.6

In [3]:
df1['timestamp'] = pd.to_datetime(df1.timestamp,unit='s')

In [4]:
df1

,timestamp,weather_id,main,description,temperature,humidity,wind_speed
0,2019-02-21 10:00:00,802,Clouds,scattered clouds,285.13,76.0,3.1
1,2019-02-21 11:30:00,802,Clouds,scattered clouds,285.64,71.0,5.1
2,2019-02-21 12:00:00,802,Clouds,scattered clouds,285.64,71.0,6.2
3,2019-02-21 12:30:00,802,Clouds,scattered clouds,285.64,66.0,5.7
4,2019-02-21 15:00:00,803,Clouds,broken clouds,286.15,62.0,8.2
5,2019-02-21 15:30:00,803,Clouds,broken clouds,286.15,62.0,8.7
6,2019-02-21 16:00:00,803,Clouds,broken clouds,286.15,62.0,8.2
7,2019-02-21 16:30:00,803,Clouds,broken clouds,285.15,66.0,7.7
8,2019-02-21 17:00:00,803,Clouds,broken clouds,284.15,71.0,6.2
9,2019-02-21 17:30:00,803,Clouds,broken clouds,284.15,71.0,7.2
10,2019-02-21 18:00:00,803,Clouds,broken clouds,284.15,71.0,6.7
11,2019-02-21 18:30:00,803,Clouds,broken clouds,284.15,71.0,4.6
12,2019-02-21 19:00:00,803,Clouds,broken clouds,283.15,76.0,5.7
13,2019-02-21 19:30:00,803,Clouds,broken clouds,283.15,76.0,4.1
14,2019-02-21 20:00:00,803,Clouds,broken clouds,283.66,81.0,6.2
15,2019-02-21 20:30:00,803,Clouds,broken clouds,284.15,76.0,7.2
16,2019-02-21 21:00:00,803,Clouds,broken clouds,283.66,81.0,7.2
17,2019-02-21 21:30:00,802,Clouds,scattered clouds,284.15,76.0,6.2
18,2019-02-21 22:00:00,801,Clouds,few clouds,283.66,87.0,5.7
19,2019-02-21 22:30:00,801,Clouds,few clouds,284.15,76.0,3.1
20,2019-02-21 23:00:00,802,Clouds,scattered clouds,284.66,81.0,3.1
21,2019-02-21 23:30:00,802,Clouds,scattered clouds,284.29,87.0,3.1
22,2019-02-22 00:00:00,803,Clouds,broken clouds,284.68,81.0,4.1
23,2019-02-22 00:30:00,802,Clouds,scattered clouds,284.42,87.0,4.1
24,2019-02-22 01:00:00,802,Clouds,scattered clouds,284.70,87.0,2.1
25,2019-02-22 01:30:00,803,Clouds,broken clouds,286.72,58.0,8.2
26,2019-02-22 02:00:00,803,Clouds,broken clouds,286.66,62.0,9.8
27,2019-02-22 02:30:00,803,Clouds,broken clouds,285.86,71.0,9.8
28,2019-02-22 03:00:00,803,Clouds,broken clouds,286.17,66.0,8.7
29,2019-02-22 03:30:00,803,Clouds,broken clouds,286.29,62.0,9.8
...,...,...,...,...,...,...,...
1739,2019-03-21 06:08:50,803,Clouds,broken clouds,283.37,87.0,3.6
1740,2019-03-21 06:28:39,803,Clouds,broken clouds,283.26,87.0,4.6
1741,2019-03-21 06:53:35,803,Clouds,broken clouds,283.26,87.0,4.6
1742,2019-03-21 07:13:35,803,Clouds,broken clouds,283.15,81.0,5.1
1743,2019-03-21 07:28:56,310,Drizzle,light intensity drizzle rain,283.15,81.0,3.6
1744,2019-03-21 07:53:40,310,Drizzle,light intensity drizzle rain,283.36,87.0,3.6
1745,2019-03-21 08:13:45,310,Drizzle,light intensity drizzle rain,283.36,87.0,3.6
1746,2019-03-21 08:23:38,803,Clouds,broken clouds,283.67,81.0,3.1
1747,2019-03-21 08:53:54,803,Clouds,broken clouds,284.06,81.0,3.6
1748,2019-03-21 09:13:47,803,Clouds,broken clouds,284.06,81.0,3.6
1749,2019-03-21 09:33:44,803,Clouds,broken clouds,284.33,81.0,3.6
1750,2019-03-21 09:53:48,803,Clouds,broken clouds,284.48,81.0,3.6
1751,2019-03-21 10:13:36,500,Rain,light rain,284.33,81.0,3.6
1752,2019-03-21 10:33:55,300,Drizzle,light intensity drizzle,284.86,71.0,3.6
1753,2019-03-21 10:53:41,300,Drizzle,light intensity drizzle,285.09,71.0,3.6
1754,2019-03-21 11:13:35,803,Clouds,broken clouds,285.09,76.0,3.6
1755,2019-03-21 11:33:48,803,Clouds,broken clouds,285.55,76.0,2.6
1756,2019-03-21 11:53:33,803,Clouds,broken clouds,285.76,76.0,2.6
1757,2019-03-21 12:08:46,803,Clouds,broken clouds,285.97,76.0,3.6
1758,2019-03-21 12:33:41,803,Clouds,broken clouds,286.07,76.0,3.1
1759,2019-03-21 12:53:45,803,Clouds,broken clouds,286.09,76.0,3.6
1760,2019-03-21 13:08:44,803,Clouds,broken clouds,285.96,76.0,3.6
1761,2019-03-21 13:33:37,803,Clouds,broken clouds,286.15,71.0,3.6
1762,2019-03-21 13:53:41,803,Clouds,broken clouds,286.35,71.0,2.6
1763,2019-03-21 14:13:41,803,Clouds,broken clouds,286.35,71.0,2.6
1764,2019-03-21 14:28:46,803,Clouds,broken clouds,286.54,71.0,3.1
1765,2019-03-21 14:53:48,803,Clouds,broken clouds,286.46,76.0,3.6
1766,2019-03-21 15:08:43,803,Clouds,broken clouds,286.58,76.0,3.6
1767,2019-03-21 15:33:40,803,Clouds,broken clouds,286.46,71.0,3.6
1768,2019-03-21 15:53:51,803,Clouds,broken clouds,286.45,71.0,3.6

In [5]:
import pymysql
from pandas import DataFrame
import pandas as pd 

host   = 'villagebikesdb.c2v2pmaab8cg.us-east-2.rds.amazonaws.com'
port   = 3306
user   = 'ssk'
passwd = 'villagebikes'
db     = 'VillageBikesDB'

cnx    = pymysql.connect(host=host, port=port, user=user, passwd=passwd, db=db)
cur    = cnx.cursor()

query  = """SELECT * FROM dynamicData"""
cur.execute(query)

field_names = [i[0] for i in cur.description]
get_data = [xx for xx in cur]

cur.close()
cnx.close()

df2 = DataFrame(get_data)
df2.columns = field_names
df2

,number,name,status,bike_stands,available_bikes,available_stands,last_update,banking
0,2,BLESSINGTON STREET,OPEN,20,3,17,1550767646000,1
1,2,BLESSINGTON STREET,OPEN,20,3,17,1550768255000,1
2,2,BLESSINGTON STREET,OPEN,20,3,17,1550768863000,1
3,2,BLESSINGTON STREET,OPEN,20,4,16,1550769472000,1
4,2,BLESSINGTON STREET,OPEN,20,4,16,1550769841000,1
5,2,BLESSINGTON STREET,OPEN,20,3,17,1550769894000,1
6,2,BLESSINGTON STREET,OPEN,20,3,17,1550769906000,1
7,2,BLESSINGTON STREET,OPEN,20,3,17,1550770212000,1
8,2,BLESSINGTON STREET,OPEN,20,3,17,1550770821000,1
9,2,BLESSINGTON STREET,OPEN,20,4,16,1550771119000,1
10,2,BLESSINGTON STREET,OPEN,20,4,16,1550771281000,1
11,2,BLESSINGTON STREET,OPEN,20,3,17,1550771335000,1
12,2,BLESSINGTON STREET,OPEN,20,3,17,1550771382000,1
13,2,BLESSINGTON STREET,OPEN,20,2,18,1550771937000,1
14,2,BLESSINGTON STREET,OPEN,20,2,18,1550771952000,1
15,2,BLESSINGTON STREET,OPEN,20,2,18,1550772055000,1
16,2,BLESSINGTON STREET,OPEN,20,3,17,1550772116000,1
17,2,BLESSINGTON STREET,OPEN,20,3,17,1550772346000,1
18,2,BLESSINGTON STREET,OPEN,20,3,17,1550772372000,1
19,2,BLESSINGTON STREET,OPEN,20,3,17,1550772531000,1
20,2,BLESSINGTON STREET,OPEN,20,2,18,1550772562000,1
21,2,BLESSINGTON STREET,OPEN,20,2,18,1550772887000,1
22,2,BLESSINGTON STREET,OPEN,20,3,17,1550772993000,1
23,2,BLESSINGTON STREET,OPEN,20,4,16,1550773295000,1
24,2,BLESSINGTON STREET,OPEN,20,4,16,1550773555000,1
25,2,BLESSINGTON STREET,OPEN,20,5,15,1550773602000,1
26,2,BLESSINGTON STREET,OPEN,20,5,15,1550773974000,1
27,2,BLESSINGTON STREET,OPEN,20,4,16,1550774631000,1
28,2,BLESSINGTON STREET,OPEN,20,4,16,1550774665000,1
29,2,BLESSINGTON STREET,OPEN,20,4,16,1550774748000,1
...,...,...,...,...,...,...,...,...
652329,115,KILLARNEY STREET,OPEN,30,17,13,1552727938000,0
652330,115,KILLARNEY STREET,OPEN,30,17,13,1552728219000,0
652331,115,KILLARNEY STREET,OPEN,30,17,13,1552728827000,0
652332,115,KILLARNEY STREET,OPEN,30,17,13,1552729436000,0
652333,115,KILLARNEY STREET,OPEN,30,17,13,1552730015000,0
652334,115,KILLARNEY STREET,OPEN,30,16,14,1552730624000,0
652335,115,KILLARNEY STREET,OPEN,30,16,14,1552731232000,0
652336,115,KILLARNEY STREET,OPEN,30,16,14,1552731621000,0
652337,115,KILLARNEY STREET,OPEN,30,16,14,1552731931000,0
652338,115,KILLARNEY STREET,OPEN,30,17,13,1552732551000,0
652339,115,KILLARNEY STREET,OPEN,30,16,14,1552733159000,0
652340,115,KILLARNEY STREET,OPEN,30,16,14,1552733768000,0
652341,115,KILLARNEY STREET,OPEN,30,18,12,1552734294000,0
652342,115,KILLARNEY STREET,OPEN,30,18,12,1552734902000,0
652343,115,KILLARNEY STREET,OPEN,30,18,12,1552735304000,0
652344,115,KILLARNEY STREET,OPEN,30,18,12,1552735404000,0
652345,115,KILLARNEY STREET,OPEN,30,17,13,1552736012000,0
652346,115,KILLARNEY STREET,OPEN,30,17,13,1552736620000,0
652347,115,KILLARNEY STREET,OPEN,30,17,13,1552737229000,0
652348,115,KILLARNEY STREET,OPEN,30,17,13,1552737837000,0
652349,115,KILLARNEY STREET,OPEN,30,17,13,1552738494000,0
652350,115,KILLARNEY STREET,OPEN,30,17,13,1552738547000,0
652351,115,KILLARNEY STREET,OPEN,30,16,14,1552738607000,0
652352,115,KILLARNEY STREET,OPEN,30,15,15,1552739215000,0
652353,115,KILLARNEY STREET,OPEN,30,15,15,1552739620000,0
652354,115,KILLARNEY STREET,OPEN,30,14,16,1552739653000,0
652355,115,KILLARNEY STREET,OPEN,30,15,15,1552740058000,0
652356,115,KILLARNEY STREET,OPEN,30,15,15,1552740114000,0
652357,115,KILLARNEY STREET,OPEN,30,14,16,1552740145000,0
652358,115,KILLARNEY STREET,OPEN,30,14,16,1552740754000,0

In [6]:
df2['last_update'] = pd.to_datetime(df2.last_update, unit='ms')

In [7]:
df2

,number,name,status,bike_stands,available_bikes,available_stands,last_update,banking
0,2,BLESSINGTON STREET,OPEN,20,3,17,2019-02-21 16:47:26,1
1,2,BLESSINGTON STREET,OPEN,20,3,17,2019-02-21 16:57:35,1
2,2,BLESSINGTON STREET,OPEN,20,3,17,2019-02-21 17:07:43,1
3,2,BLESSINGTON STREET,OPEN,20,4,16,2019-02-21 17:17:52,1
4,2,BLESSINGTON STREET,OPEN,20,4,16,2019-02-21 17:24:01,1
5,2,BLESSINGTON STREET,OPEN,20,3,17,2019-02-21 17:24:54,1
6,2,BLESSINGTON STREET,OPEN,20,3,17,2019-02-21 17:25:06,1
7,2,BLESSINGTON STREET,OPEN,20,3,17,2019-02-21 17:30:12,1
8,2,BLESSINGTON STREET,OPEN,20,3,17,2019-02-21 17:40:21,1
9,2,BLESSINGTON STREET,OPEN,20,4,16,2019-02-21 17:45:19,1
10,2,BLESSINGTON STREET,OPEN,20,4,16,2019-02-21 17:48:01,1
11,2,BLESSINGTON STREET,OPEN,20,3,17,2019-02-21 17:48:55,1
12,2,BLESSINGTON STREET,OPEN,20,3,17,2019-02-21 17:49:42,1
13,2,BLESSINGTON STREET,OPEN,20,2,18,2019-02-21 17:58:57,1
14,2,BLESSINGTON STREET,OPEN,20,2,18,2019-02-21 17:59:12,1
15,2,BLESSINGTON STREET,OPEN,20,2,18,2019-02-21 18:00:55,1
16,2,BLESSINGTON STREET,OPEN,20,3,17,2019-02-21 18:01:56,1
17,2,BLESSINGTON STREET,OPEN,20,3,17,2019-02-21 18:05:46,1
18,2,BLESSINGTON STREET,OPEN,20,3,17,2019-02-21 18:06:12,1
19,2,BLESSINGTON STREET,OPEN,20,3,17,2019-02-21 18:08:51,1
20,2,BLESSINGTON STREET,OPEN,20,2,18,2019-02-21 18:09:22,1
21,2,BLESSINGTON STREET,OPEN,20,2,18,2019-02-21 18:14:47,1
22,2,BLESSINGTON STREET,OPEN,20,3,17,2019-02-21 18:16:33,1
23,2,BLESSINGTON STREET,OPEN,20,4,16,2019-02-21 18:21:35,1
24,2,BLESSINGTON STREET,OPEN,20,4,16,2019-02-21 18:25:55,1
25,2,BLESSINGTON STREET,OPEN,20,5,15,2019-02-21 18:26:42,1
26,2,BLESSINGTON STREET,OPEN,20,5,15,2019-02-21 18:32:54,1
27,2,BLESSINGTON STREET,OPEN,20,4,16,2019-02-21 18:43:51,1
28,2,BLESSINGTON STREET,OPEN,20,4,16,2019-02-21 18:44:25,1
29,2,BLESSINGTON STREET,OPEN,20,4,16,2019-02-21 18:45:48,1
...,...,...,...,...,...,...,...,...
652329,115,KILLARNEY STREET,OPEN,30,17,13,2019-03-16 09:18:58,0
652330,115,KILLARNEY STREET,OPEN,30,17,13,2019-03-16 09:23:39,0
652331,115,KILLARNEY STREET,OPEN,30,17,13,2019-03-16 09:33:47,0
652332,115,KILLARNEY STREET,OPEN,30,17,13,2019-03-16 09:43:56,0
652333,115,KILLARNEY STREET,OPEN,30,17,13,2019-03-16 09:53:35,0
652334,115,KILLARNEY STREET,OPEN,30,16,14,2019-03-16 10:03:44,0
652335,115,KILLARNEY STREET,OPEN,30,16,14,2019-03-16 10:13:52,0
652336,115,KILLARNEY STREET,OPEN,30,16,14,2019-03-16 10:20:21,0
652337,115,KILLARNEY STREET,OPEN,30,16,14,2019-03-16 10:25:31,0
652338,115,KILLARNEY STREET,OPEN,30,17,13,2019-03-16 10:35:51,0
652339,115,KILLARNEY STREET,OPEN,30,16,14,2019-03-16 10:45:59,0
652340,115,KILLARNEY STREET,OPEN,30,16,14,2019-03-16 10:56:08,0
652341,115,KILLARNEY STREET,OPEN,30,18,12,2019-03-16 11:04:54,0
652342,115,KILLARNEY STREET,OPEN,30,18,12,2019-03-16 11:15:02,0
652343,115,KILLARNEY STREET,OPEN,30,18,12,2019-03-16 11:21:44,0
652344,115,KILLARNEY STREET,OPEN,30,18,12,2019-03-16 11:23:24,0
652345,115,KILLARNEY STREET,OPEN,30,17,13,2019-03-16 11:33:32,0
652346,115,KILLARNEY STREET,OPEN,30,17,13,2019-03-16 11:43:40,0
652347,115,KILLARNEY STREET,OPEN,30,17,13,2019-03-16 11:53:49,0
652348,115,KILLARNEY STREET,OPEN,30,17,13,2019-03-16 12:03:57,0
652349,115,KILLARNEY STREET,OPEN,30,17,13,2019-03-16 12:14:54,0
652350,115,KILLARNEY STREET,OPEN,30,17,13,2019-03-16 12:15:47,0
652351,115,KILLARNEY STREET,OPEN,30,16,14,2019-03-16 12:16:47,0
652352,115,KILLARNEY STREET,OPEN,30,15,15,2019-03-16 12:26:55,0
652353,115,KILLARNEY STREET,OPEN,30,15,15,2019-03-16 12:33:40,0
652354,115,KILLARNEY STREET,OPEN,30,14,16,2019-03-16 12:34:13,0
652355,115,KILLARNEY STREET,OPEN,30,15,15,2019-03-16 12:40:58,0
652356,115,KILLARNEY STREET,OPEN,30,15,15,2019-03-16 12:41:54,0
652357,115,KILLARNEY STREET,OPEN,30,14,16,2019-03-16 12:42:25,0
652358,115,KILLARNEY STREET,OPEN,30,14,16,2019-03-16 12:52:34,0

In [11]:
df1['just_date'] = df1['timestamp'].dt.date

In [13]:
df2['just_date'] = df2['last_update'].dt.date

In [15]:
df1['hour'] = df1['timestamp'].dt.hour

In [16]:
df1['hour'] = df1['hour'].astype('str')

In [17]:
df1['just_date'] = df1['just_date'].astype('str')

In [25]:
df2['hour'] = df2['last_update'].dt.hour

In [26]:
df2['hour'] = df2['hour'].astype('str')

In [27]:
df2['just_date'] = df2['just_date'].astype('str')

In [40]:
df = pd.merge(df1, df2, on = ['just_date', 'hour'],  how = 'left')

In [42]:
df

,timestamp,weather_id,main,description,temperature,humidity,wind_speed,just_date,hour,date_hour_x,number,name,status,bike_stands,available_bikes,available_stands,last_update,banking,date_hour_y
0,2019-02-21 10:00:00,802,Clouds,scattered clouds,285.13,76.0,3.1,2019-02-21,10,2019-02-21 10,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN
1,2019-02-21 11:30:00,802,Clouds,scattered clouds,285.64,71.0,5.1,2019-02-21,11,2019-02-21 11,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN
2,2019-02-21 12:00:00,802,Clouds,scattered clouds,285.64,71.0,6.2,2019-02-21,12,2019-02-21 12,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN
3,2019-02-21 12:30:00,802,Clouds,scattered clouds,285.64,66.0,5.7,2019-02-21,12,2019-02-21 12,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN
4,2019-02-21 15:00:00,803,Clouds,broken clouds,286.15,62.0,8.2,2019-02-21,15,2019-02-21 15,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN
5,2019-02-21 15:30:00,803,Clouds,broken clouds,286.15,62.0,8.7,2019-02-21,15,2019-02-21 15,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN
6,2019-02-21 16:00:00,803,Clouds,broken clouds,286.15,62.0,8.2,2019-02-21,16,2019-02-21 16,2.0,BLESSINGTON STREET,OPEN,20.0,3.0,17.0,2019-02-21 16:47:26,1.0,2019-02-21 10
7,2019-02-21 16:00:00,803,Clouds,broken clouds,286.15,62.0,8.2,2019-02-21,16,2019-02-21 16,2.0,BLESSINGTON STREET,OPEN,20.0,3.0,17.0,2019-02-21 16:57:35,1.0,2019-02-21 11
8,2019-02-21 16:00:00,803,Clouds,broken clouds,286.15,62.0,8.2,2019-02-21,16,2019-02-21 16,3.0,BOLTON STREET,OPEN,20.0,0.0,20.0,2019-02-21 16:49:04,0.0,NaN
9,2019-02-21 16:00:00,803,Clouds,broken clouds,286.15,62.0,8.2,2019-02-21,16,2019-02-21 16,3.0,BOLTON STREET,OPEN,20.0,0.0,20.0,2019-02-21 16:59:13,0.0,NaN
10,2019-02-21 16:00:00,803,Clouds,broken clouds,286.15,62.0,8.2,2019-02-21,16,2019-02-21 16,4.0,GREEK STREET,OPEN,20.0,0.0,20.0,2019-02-21 16:54:08,0.0,NaN
11,2019-02-21 16:00:00,803,Clouds,broken clouds,286.15,62.0,8.2,2019-02-21,16,2019-02-21 16,5.0,CHARLEMONT PLACE,OPEN,40.0,16.0,24.0,2019-02-21 16:54:41,0.0,NaN
12,2019-02-21 16:00:00,803,Clouds,broken clouds,286.15,62.0,8.2,2019-02-21,16,2019-02-21 16,5.0,CHARLEMONT PLACE,OPEN,40.0,20.0,20.0,2019-02-21 16:59:32,0.0,NaN
13,2019-02-21 16:00:00,803,Clouds,broken clouds,286.15,62.0,8.2,2019-02-21,16,2019-02-21 16,6.0,CHRISTCHURCH PLACE,OPEN,20.0,0.0,20.0,2019-02-21 16:52:04,0.0,NaN
14,2019-02-21 16:00:00,803,Clouds,broken clouds,286.15,62.0,8.2,2019-02-21,16,2019-02-21 16,7.0,HIGH STREET,OPEN,29.0,0.0,29.0,2019-02-21 16:49:51,1.0,NaN
15,2019-02-21 16:00:00,803,Clouds,broken clouds,286.15,62.0,8.2,2019-02-21,16,2019-02-21 16,8.0,CUSTOM HOUSE QUAY,OPEN,30.0,30.0,0.0,2019-02-21 16:55:00,0.0,NaN
16,2019-02-21 16:00:00,803,Clouds,broken clouds,286.15,62.0,8.2,2019-02-21,16,2019-02-21 16,8.0,CUSTOM HOUSE QUAY,OPEN,30.0,29.0,1.0,2019-02-21 16:59:52,0.0,NaN
17,2019-02-21 16:00:00,803,Clouds,broken clouds,286.15,62.0,8.2,2019-02-21,16,2019-02-21 16,9.0,EXCHEQUER STREET,OPEN,24.0,11.0,13.0,2019-02-21 16:54:38,0.0,NaN
18,2019-02-21 16:00:00,803,Clouds,broken clouds,286.15,62.0,8.2,2019-02-21,16,2019-02-21 16,9.0,EXCHEQUER STREET,OPEN,24.0,15.0,9.0,2019-02-21 16:59:54,0.0,NaN
19,2019-02-21 16:00:00,803,Clouds,broken clouds,286.15,62.0,8.2,2019-02-21,16,2019-02-21 16,10.0,DAME STREET,OPEN,16.0,0.0,16.0,2019-02-21 16:48:59,1.0,NaN
20,2019-02-21 16:00:00,803,Clouds,broken clouds,286.15,62.0,8.2,2019-02-21,16,2019-02-21 16,10.0,DAME STREET,OPEN,16.0,2.0,14.0,2019-02-21 16:59:49,1.0,NaN
21,2019-02-21 16:00:00,803,Clouds,broken clouds,286.15,62.0,8.2,2019-02-21,16,2019-02-21 16,11.0,EARLSFORT TERRACE,OPEN,30.0,0.0,30.0,2019-02-21 16:53:09,0.0,NaN
22,2019-02-21 16:00:00,803,Clouds,broken clouds,286.15,62.0,8.2,2019-02-21,16,2019-02-21 16,12.0,ECCLES STREET,OPEN,20.0,4.0,16.0,2019-02-21 16:53:39,0.0,NaN
23,2019-02-21 16:00:00,803,Clouds,broken clouds,286.15,62.0,8.2,2019-02-21,16,2019-02-21 16,12.0,ECCLES STREET,OPEN,20.0,3.0,17.0,2019-02-21 16:57:32,0.0,NaN
24,2019-02-21 16:00:00,803,Clouds,broken clouds,286.15,62.0,8.2,2019-02-21,16,2019-02-21 16,13.0,FITZWILLIAM SQUARE WEST,OPEN,30.0,18.0,11.0,2019-02-21 16:47:08,0.0,NaN
25,2019-02-21 16:00:00,803,Clouds,broken clouds,286.15,62.0,8.2,2019-02-21,16,2019-02-21 16,13.0,FITZWILLIAM SQUARE WEST,OPEN,30.0,17.0,12.0,2019-02-21 16:59:31,0.0,NaN
26,2019-02-21 16:00:00,803,Clouds,broken clouds,286.15,62.0,8.2,2019-02-21,16,2019-02-21 16,14.0,FOWNES STREET UPPER,OPEN,30.0,20.0,9.0,2019-02-21 16:54:55,0.0,NaN
27,2019-02-21 16:00:00,803,Clouds,broken clouds,286.15,62.0,8.2,2019-02-21,16,2019-02-21 16,14.0,FOWNES STREET UPPER,OPEN,30.0,20.0,9.0,2019-02-21 16:59:58,0.0,NaN
28,2019-02-21 16:00:00,803,Clouds,broken clouds,286.15,62.0,8.2,2019-02-21,16,2019-02-21 16,15.0,HARDWICKE STREET,OPEN,16.0,0.0,16.0,2019-02-21 16:49:29,0.0,NaN
29,2019-02-21 16:00:00,803,Clouds,broken clouds,286.15,62.0,8.2,2019-02-21,16,2019-02-21 16,15.0,HARDWICKE STREET,OPEN,16.0,0.0,16.0,2019-02-21 16:58:27,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1636724,2019-03-21 06:08:50,803,Clouds,broken clouds,283.37,87.0,3.6,2019-03-21,6,2019-03-21 6,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN
1636725,2019-03-21 06:28:39,803,Clouds,broken clouds,283.26,87.0,4.6,2019-03-21,6,2019-03-21 6,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN
1636726,2019-03-21 06:53:35,803,Clouds,broken clouds,283.26,87.0,4.6,2019-03-21,6,2019-03-21 6,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN
1636727,2019-03-21 07:13:35,803,Clouds,broken clouds,283.15,81.0,5.1,2019-03-21,7,2019-03-21 7,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN
1636728,2019-03-21 07:28:56,310,Drizzle,light intensity drizzle rain,283.15,81.0,3.6,2019-03-21,7,2019-03-21 7,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN
1636729,2019-03-21 07:53:40,310,Drizzle,light intensity drizzle rain,283.36,87.0,3.6,2019-03-21,7,2019-03-21 7,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN
1636730,2019-03-21 08:13:45,310,Drizzle,light intensity drizzle rain,283.36,87.0,3.6,2019-03-21,8,2019-03-21 8,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN
1636731,2019-03-21 08:23:38,803,Clouds,broken clouds,283.67,81.0,3.1,2019-03-21,8,2019-03-21 8,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN
1636732,2019-03-21 08:53:54,803,Clouds,broken clouds,284.06,81.0,3.6,2019-03-21,8,2019-03-21 8,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN
1636733,2019-03-21 09:13:47,803,Clouds,broken clouds,284.06,81.0,3.6,2019-03-21,9,2019-03-21 9,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN
1636734,2019-03-21 09:33:44,803,Clouds,broken clouds,284.33,81.0,3.6,2019-03-21,9,2019-03-21 9,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN
1636735,2019-03-21 09:53:48,803,Clouds,broken clouds,284.48,81.0,3.6,2019-03-21,9,2019-03-21 9,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN
1636736,2019-03-21 10:13:36,500,Rain,light rain,284.33,81.0,3.6,2019-03-21,10,2019-03-21 10,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN
1636737,2019-03-21 10:33:55,300,Drizzle,light intensity drizzle,284.86,71.0,3.6,2019-03-21,10,2019-03-21 10,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN
1636738,2019-03-21 10:53:41,300,Drizzle,light intensity drizzle,285.09,71.0,3.6,2019-03-21,10,2019-03-21 10,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN
1636739,2019-03-21 11:13:35,803,Clouds,broken clouds,285.09,76.0,3.6,2019-03-21,11,2019-03-21 11,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN
1636740,2019-03-21 11:33:48,803,Clouds,broken clouds,285.55,76.0,2.6,2019-03-21,11,2019-03-21 11,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN
1636741,2019-03-21 11:53:33,803,Clouds,broken clouds,285.76,76.0,2.6,2019-03-21,11,2019-03-21 11,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN
1636742,2019-03-21 12:08:46,803,Clouds,broken clouds,285.97,76.0,3.6,2019-03-21,12,2019-03-21 12,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN
1636743,2019-03-21 12:33:41,803,Clouds,broken clouds,286.07,76.0,3.1,2019-03-21,12,2019-03-21 12,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN
1636744,2019-03-21 12:53:45,803,Clouds,broken clouds,286.09,76.0,3.6,2019-03-21,12,2019-03-21 12,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN
1636745,2019-03-21 13:08:44,803,Clouds,broken clouds,285.96,76.0,3.6,2019-03-21,13,2019-03-21 13,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN
1636746,2019-03-21 13:33:37,803,Clouds,broken clouds,286.15,71.0,3.6,2019-03-21,13,2019-03-21 13,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN
1636747,2019-03-21 13:53:41,803,Clouds,broken clouds,286.35,71.0,2.6,2019-03-21,13,2019-03-21 13,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN
1636748,2019-03-21 14:13:41,803,Clouds,broken clouds,286.35,71.0,2.6,2019-03-21,14,2019-03-21 14,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN
1636749,2019-03-21 14:28:46,803,Clouds,broken clouds,286.54,71.0,3.1,2019-03-21,14,2019-03-21 14,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN
1636750,2019-03-21 14:53:48,803,Clouds,broken clouds,286.46,76.0,3.6,2019-03-21,14,2019-03-21 14,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN
1636751,2019-03-21 15:08:43,803,Clouds,broken clouds,286.58,76.0,3.6,2019-03-21,15,2019-03-21 15,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN
1636752,2019-03-21 15:33:40,803,Clouds,broken clouds,286.46,71.0,3.6,2019-03-21,15,2019-03-21 15,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN
1636753,2019-03-21 15:53:51,803,Clouds,broken clouds,286.45,71.0,3.6,2019-03-21,15,2019-03-21 15,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN

In [41]:
df.to_csv('first_test.csv')